name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v
    - name: make
      run: make
